---
title: "Assigned Reading and Extra Problems"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Reading

## Week 1-2
Lecture 1, Chapter 1: Sections 1.1 - 1.3 p. 5 - 34

Lecture 2, Chapter 2: Sections 2.1 - 2.2 p. 67 - 86

## Week 2-4
Chapter 2: Sections 2.3 - 2.8 p. 87 - 174

## Week 5
Chapter 6: Section 6.1 p. 365 - 370

Chapter 1: Sections 1.4 - 1.6 p. 35 - 66 

## Week 6

Chapter 3: All sections p. 175 - 244

Chapter 4: Sections 4.1 - 4.3, 4.6 p.243 - 258 and p.266 - 270 

## Week 7 - 8

Chapter 5: Sections 5.1 p.311 - 315

Chapter 6: Sections 6.2 - 6.4, p.371 - 398

Chapter 7: All Sections p. 399 - 442

Week 9 - 12: 

Chapter 8: All sections p. 443 - 504

Chapter 9: All sections p. 505 - 566
 
 
# Extra Problems
Week 1-4, Appendix A: Chapter 3 Review problems
 
Week 5: 

  * Practice problems chapter 1 p. 52 problems 40 and 41

  * Homework problems chapter 1 p. 59 - 60 problems 87 - 90

  * Practice problems chapter 6 p. 384 - 386. 1-42
  
Week 6: 

  * Practice problems chapter 3 p. 215 - 219, problems 1-35, 36-37, 39, 44-45, 48-49,51-53, 54-57
  
  * homework problems chapter 3 p. 219 - , problems 66-79, 81-84, 87-89, 91, 94-99, 101-110, 112
  
Week 7:

  * Practice problems chapter 4 p. 281 - 287, problems 1-44, 56-68
  
  * homework problems chapter 4 p. 288 - 299, problems 69-103, 117-129
  
  * Practice problems chapter 5 p. 345 - 346, problems 3-15
  
  * homework problems chapter 5 p. 352, problems 72-73

  
Week 8:

  * Practice problems chapter 6 p. 386 - 388, problems 43 - 59

  * homework problems chapter 6 p. 389 - , problems 60-61, 63-88
  
  * Practice problems chapter 7 p. 426 - 430, All problems

  * homework problems chapter 7 p. 430 - 438, All problems 
  
Week 9 - 12: 

  * Practice problems chapter 8 all problems

  * homework problems chapter 8 all problems
  
  * Practice problems chapter 9 all problems

  * homework problems chapter 9 all problems 
