---
title: "Course Schedule"
output:
  html_document: default
header-includes: \usepackage{float} \usepackage{hyperref}
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<table border="1" cellspacing="10" style="width:50%">
    <tr>
        <td>**WEEK 1**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday </td>
        <td>January 8, 2024</td>
        <td>NO CLASS</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>January 10, 2024</td>
        <td>Introduction: The big picture</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>January 12, 2024</td>
        <td>Describing and visualizing distributions</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 2**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>January 15, 2024</td>
        <td>No Class </td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>January 17, 2024</td>
        <td>CLASS CANCELED - Flooding TLC</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>January 19, 2024</td>
        <td>Describing and visualizing distributions (continued)</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 3**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>January 22, 2024</td>
        <td>The normal distribution</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>January 24, 2024</td>
        <td>transformations, z-scores</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>January 26, 2024</td>
        <td>Identifying outliers, margin of error</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 4**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>January 29, 2024</td>
        <td>Study and sampling designs </td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>January 31, 2024</td>
        <td>Exam 1 Review </td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>February 2, 2024</td>
        <td>Exam 1 </td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 5**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>February 5, 2024</td>
        <td>Introduction to Probability</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>February 7, 2024</td>
        <td>Random Variables and Discrete Probability Distributions</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>February 9, 2024</td>
        <td>Continuous probability distributions</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 6**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>February 12, 2024</td>
        <td>Sampling distributions of means and proportions</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>February 14, 2024</td>
        <td>Central Limit Theorem (CLT) and estimation</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>February 16, 2024</td>
        <td>Introduction to confidence intervals</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 7**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>February 19, 2024</td>
        <td>NO CLASS</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>February 21, 2024</td>
        <td>Confidence Intervals for a population mean   </td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>February 23, 2024</td>
        <td>Confidence Intervals for a population proportion  </td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 8**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>February 26, 2024</td>
        <td>Bootstrap confidence intervals </td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>February 28, 2024</td>
        <td>Sampling with/without replacement, estimation for a population total</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>March 1, 2024</td>
        <td>Estimation for a population total</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 9**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>March 4, 2024</td>
        <td>Choosing a minimum sample size, assumptions of estimators </td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>March 6, 2024</td>
        <td>Exam 2 Review </td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>March 8, 2024</td>
        <td>Exam 2</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 10**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>March 11, 2024</td>
        <td>Spring Recess no Class </td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>March 13, 2024</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>March 15, 2024</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 11**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>March 18, 2024</td>
        <td>Introduction to significance tests, Pvalues</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>March 20, 2024</td>
        <td>Tests for a population proportion</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>March 22, 2024</td>
        <td>NO CLASS</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 12**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>March 25, 2024</td>
        <td>Tests for a population mean</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>March 27, 2024</td>
        <td>Composite hypotheses, relationship between confidence intervals and hypothesis tests, the sign test</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>March 29, 2024</td>
        <td>Making decisions, types of errors in hypothesis test, statistical power</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 13**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>April 1, 2024</td>
        <td>Introduction to two-sample tests, independent vs dependent samples</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>April 3, 2024</td>
        <td>Tests for comparing two independent proportions or two independent means</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>April 5, 2024</td>
        <td>Tests for dependent samples, causal inference</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 14**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>April 8, 2024</td>
        <td>Introduction to analyzing categorical variables</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>April 10, 2024</td>
        <td>Goodness-of-fit tests and tests of independence</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>April 12, 2024</td>
        <td>Cramers V, McNemars Test, Fishers exact test</td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 15**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>April 15, 2024</td>
        <td>Exam 3 Review</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>April 17, 2024</td>
        <td>Exam 3</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>April 19, 2024</td>
        <td>Measures of association </td>
        <td></td>
    </tr>
    <tr>
        <td>**WEEK 16**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>April 22, 2024</td>
        <td>Correlation and simple linear regression</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>April 24, 2024</td>
        <td>Coefficient of determination, tests for slope coefficients </td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>April 26, 2024</td>
        <td>ANOVA</td>
        <td></td>
    </tr>
    <tr>
        <td>**No Exam WEEK**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>**Day**</td>
        <td>**Date**</td>
        <td>**Topic**</td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>April 29, 2024</td>
        <td>ANOVA continued</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>May 1, 2024</td>
        <td>Final exam informal review, course project due at midnight</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>May 3, 2024</td>
        <td>No Class</td>
        <td></td>
    </tr>
    <tr>
        <td>**Final Exam WEEK**</td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Monday</td>
        <td>May 6, 2024</td>
        <td>Final Exam Day, Time: 8:00 am - 10:00 am</td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Wednesday</td>
        <td>May 8, 2024</td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
    </tr>
    <tr>
        <td>Friday</td>
        <td>May 10, 2024</td>
    </tr>
</table>