---
title: "Download lecture slides here"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 1

### Lecture 1
<a href="./lecture_slides/Week 1/Week1_Lecture1_Slides_1_10_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 1/Week1_Lecture1_Slides_1_10_2024.pptx">Download File</a>
as powerpoint

### Lecture 2 
<a href="./lecture_slides/Week 1/Week1_Lecture2_Slides_1_12_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 1/Week1_Lecture2_Slides_1_12_2024.pptx">Download File</a>
as powerpoint

# Week 2

### Lecture 3
<a href="./lecture_slides/Week 2/Week2_Lecture3_Slides_1_19_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 2/Week2_Lecture3_Slides_1_19_2024.pptx">Download File</a>
as powerpoint

# Week 3

### Lecture 4
<a href="./lecture_slides/Week 3/Week3_Lecture4_Slides_1_22_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 3/Week3_Lecture4_Slides_1_22_2024.pptx">Download File</a>
as powerpoint


### Lecture 5
<a href="./lecture_slides/Week 3/Week3_Lecture5_Slides_1_24_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 3/Week3_Lecture5_Slides_1_24_2024.pptx">Download File</a>
as powerpoint

# Week 4

### Lecture 6
<a href="./lecture_slides/Week 4/Week4_Lecture6_Slides_1_29_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 4/Week4_Lecture6_Slides_1_29_2024.pptx">Download File</a>
as powerpoint

# Week 5

### Lecture 7
<a href="./lecture_slides/Week 5/Week5_Lecture7_Slides_2_5_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 5/Week5_Lecture7_Slides_2_5_2024.pptx">Download File</a>
as powerpoint

### Lecture 8
<a href="./lecture_slides/Week 5/Week5_Lecture8_Slides_2_7_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 5/Week5_Lecture8_Slides_2_7_2024.pptx">Download File</a>
as powerpoint

### Lecture 9
<a href="./lecture_slides/Week 5/Week5_Lecture9_Slides_2_9_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 5/Week5_Lecture9_Slides_2_9_2024.pptx">Download File</a>
as powerpoint

# Week 6

### Lecture 10
<a href="./lecture_slides/Week 6/Week6_Lecture10_Slides_2_12_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 6/Week6_Lecture10_Slides_2_12_2024.pptx">Download File</a>
as powerpoint

### Lecture 11
<a href="./lecture_slides/Week 6/Week6_Lecture11_Slides_2_14_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 6/Week6_Lecture11_Slides_2_14_2024.pptx">Download File</a>
as powerpoint

### Lecture 12
<a href="./lecture_slides/Week 6/Week6_Lecture12_Slides_2_16_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 6/Week6_Lecture12_Slides_2_16_2024.pptx">Download File</a>
as powerpoint

# Week 7

### Lecture 13
<a href="./lecture_slides/Week 7/Week7_Lecture13_Slides_2_21_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 7/Week7_Lecture13_Slides_2_21_2024.pptx">Download File</a>
as powerpoint

### Lecture 14
<a href="./lecture_slides/Week 7/Week7_Lecture14_Slides_2_23_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 7/Week7_Lecture14_Slides_2_23_2024.pptx">Download File</a>
as powerpoint

# Week 8

### Lecture 15
<a href="./lecture_slides/Week 8/Week8_Lecture15_Slides_2_26_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 8/Week8_Lecture15_Slides_2_26_2024.pptx">Download File</a>
as powerpoint

### Lecture 16
<a href="./lecture_slides/Week 8/Week8_Lecture16_Slides_2_28_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 8/Week8_Lecture16_Slides_2_28_2024.pptx">Download File</a>
as powerpoint


### Lecture 17
<a href="./lecture_slides/Week 8/Week8_Lecture17_Slides_3_1_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 8/Week8_Lecture17_Slides_3_1_2024.pptx">Download File</a>
as powerpoint

# Week 9

### Lecture 18
<a href="./lecture_slides/Week 9/Week9_Lecture18_Slides_3_4_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 9/Week9_Lecture18_Slides_3_4_2024.pptx">Download File</a>
as powerpoint

# Week 11 - 12

### Lecture 20 - 21
<a href="./lecture_slides/Week 11/Week11_Lecture20_Slides_3_20_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 11/Week11_Lecture20_Slides_3_20_2024.pptx">Download File</a>
as powerpoint


### Lecture 22

<a href="./lecture_slides/Week 12/Week12_Lecture22_Slides_3_27_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 12/Week12_Lecture22_Slides_3_27_2024.pptx">Download File</a>
as powerpoint

### Lecture 23

<a href="./lecture_slides/Week 12/Week12_Lecture23_Slides_3_29_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 12/Week12_Lecture23_Slides_3_29_2024.pptx">Download File</a>
as powerpoint

# Week 13

### Lecture 24

<a href="./lecture_slides/Week 13/Week13_Lecture24_Slides_4_1_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 13/Week13_Lecture24_Slides_4_1_2024.pptx">Download File</a>
as powerpoint

### Lecture 25

<a href="./lecture_slides/Week 13/Week13_Lecture25_Slides_4_3_2024.pdf">Download File</a>
as .pdf

<a href="./lecture_slides/Week 13/Week13_Lecture25_Slides_4_3_2024.pptx">Download File</a>
as powerpoint

# Week 14
### Lecture 26

