---
title: "STAT251-03 Course Project"
output: html_document
header-includes:
  \usepackage{float}
urlcolor: blue  
#bibliography: home2bibs.bib
---




```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=5, fig.height=3, fig.pos = "H")
library(kableExtra)
library(knitr)
```


## Project Description: 
This project is an optional, it is worth 20 points, and it will be due in Canvas on December 10th at midnight. All points earned will applied to the final score of your lowest kept exam. The objective of this project is to engage you in a hands-on exploration of statistical analysis. In this project you will demonstrate your understanding of the main tenets of statistical description and inference that we have learned in this class. You will start by selecting and investigating two variables from one of three provided datasets: Dataset A, Dataset B, or Dataset C which can be found (with a detailed description) on the course website on Canvas. Complete the instructions for steps 1-3 to conduct a thorough statistical analysis of your chosen variables. Write up your results as a short report (1-5 pages). You may use any statistical software available to you to analyze your chosen variables (for example: Microsoft Excel, R, SAS, Python, MATLAB, SPSS, or other). In addition, I have included several websites (links below) which can also be used to complete your analyses:

## Links:   

[Plotly for online data visualization](https://plot.ly/create/?_ga=2.215845015.1866748034.1700201169-713259889.1700201168)   

[RAWgraphs Online Data Vizualization Tool](https://www.rawgraphs.io/)

[IMathAS Boxplot Grapher](https://www.imathas.com/stattools/boxplot.html)   

[Chemgrid Boxplot Maker](http://shiny.chemgrid.org/boxplotr/)   

[National Center For Education Statistics](https://nces.ed.gov/nceskids/createagraph/)    

[Evan's Awesome AB tool (for $t$-test and $\chi^2$-test)](https://www.evanmiller.org/ab-testing/)   

[Purdue University Department of Psychology Free 2-proportion Z-test Calculator](http://www2.psych.purdue.edu/~gfrancis/calculators/proportion_test_two_sample.shtml)   

[LibreTexts Chi-Square Goodness of Fit Test Calculator](https://stats.libretexts.org/Learning_Objects/02%3A_Interactive_Statistics/36%3A__Chi-Square_Goodness_of_Fit_Test_Calculator)

[LibreTexts Chi-Square Test of Independence Calculator](https://stats.libretexts.org/Learning_Objects/02%3A_Interactive_Statistics/37%3A__Chi-Square_Test_For_Independence_Calculator)   

[Virginia Tech Sign Test Calculator](https://camel.psyc.vt.edu/models/stats/sign_test.shtml)


## Key Learning Objectives: 
Gain proficiency in selecting and handling real-world datasets.
Develop skills in using descriptive statistics to characterize the distribution of variables.
Formulate testable hypotheses based on observed patterns or relationships in the data.
Apply appropriate statistical tests to evaluate hypotheses and draw meaningful conclusions.
Enhance data visualization skills through the creation of descriptive plots.


## Assessment Criteria:

* Clarity and relevance of the chosen statistical question.
* Accuracy and completeness of the statistical description for each variable.
* Appropriateness of the chosen hypothesis and statistical test.
* Accuracy in conducting the statistical test and interpreting the results.
* Presentation quality of descriptive plots and written analysis.

## Deliverables:


* A written report documenting your entire statistical process, including the statistical question, descriptive statistics, hypothesis formulation, statistical test application, and conclusion.
* Visualizations of the chosen variables' distributions.
* Any additional insights or observations gained during the analysis.
* This project is designed to foster a deeper understanding of statistical concepts through practical application and encourages critical thinking in formulating and testing hypotheses based on real-world data.

Please read all instructions carefully


# Project Steps:

## 1. Variable Selection:

Choose two variables from one of the provided datasets (A, B, or C) and articulate a statistical question related to these variables. One of the variables should be qualitative. The other variable can be either quantitative or qualitative. Write a short description of the question you are interested in exploring and how the two variables are related to that question (i.e describe in words what each variable is).

## 2. Statistical Description:

* **(A)** Utilizing descriptive statistics, provide a comprehensive overview of each selected variable. For quantitative variables, compute the **minimum, Q1, median, mean, Q3, maximum, interquartile range (IQR), and the standard deviation** and provide them in a table format (see below). For categorical variables, construct a **frequency table** and identify the **modal category**.


| **Statistic**       | **Value** |
| :------------------ | :-------  |
| minimum             |           |
| Q1                  |           |
| median              |           |
| mean                |           |
| Q3                  |           |
| maximum             |           |
| interquartile range |           |
| standard deviation  |           |



* **(B)** Create at least one descriptive plot for each variable: (e.g., histogram, boxplot, dot plot, stem-and-leaf plot, pareto chart, pie chart, bar chart) to visualize their distribution.


* **(C)** Using the descriptive statistics computed in parts A and B, write a short description of the shape, center, and variability of your chosen variables and make note of any outliers. 

## 3. Hypothesis Formulation and Testing:
Building on the statistical description in **Part 2.**, formulate a testable hypothesis (or multiple if you analyze the variables separately) related to your question in **Part 1** that explores the relationship between the chosen variables. Depending on the nature of your question, be sure to choose the appropriate statistical test. This may include any of the tests we have talked about in class including: tests of means, proportions, or categorical tests such as one of the $\chi^2$-tests or other relevant tests such as one of the non-parametric tests we've discussed. 


* **(A)** Write a short description justifying your choice of hypothesis test and how it will help you answer the statistical question you outline in **Part 1**. Address any assumptions of the test and whether you data adheres to the assumptions. State the null and alternative hypotheses.

* **(B)** Conduct the chosen statistical test: Give the critical value, degrees of freedom (if applicable), test statistic and $pvalue$ of the test. 
* **(C)** Interpret the results of your test and draw conclusions regarding the validity or rejection of the hypothesis. 


